import AsyncStorage from '@react-native-async-storage/async-storage';
import { Feather } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useColors } from '@/hooks/useColors';

type Reminder = { id: string; text: string; done: boolean };
export default function RemindersScreen() {
  const colors = useColors();
  const [items, setItems] = useState<Reminder[]>([]);
  const [text, setText] = useState('');
  useEffect(() => { AsyncStorage.getItem('jarvis-reminders').then((v) => v && setItems(JSON.parse(v) as Reminder[])); }, []);
  const persist = (next: Reminder[]) => { setItems(next); AsyncStorage.setItem('jarvis-reminders', JSON.stringify(next)); };
  const add = () => { if (!text.trim()) return; persist([{ id: `${Date.now()}`, text: text.trim(), done: false }, ...items]); setText(''); };
  return <View style={[styles.screen, { backgroundColor: colors.background }]}><Text style={[styles.heading, { color: colors.foreground }]}>Reminders</Text><Text style={[styles.subheading, { color: colors.mutedForeground }]}>Small nudges for the things that matter.</Text><View style={[styles.addRow, { backgroundColor: colors.card, borderColor: colors.border }]}><TextInput value={text} onChangeText={setText} onSubmitEditing={add} placeholder="What should Jarvis remind you?" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} /><Pressable onPress={add} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={20} color={colors.primaryForeground} /></Pressable></View><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={[styles.empty, { color: colors.mutedForeground }]}>No reminders yet. Add one above.</Text>} renderItem={({ item }) => <View style={[styles.item, { backgroundColor: colors.card, borderColor: colors.border }]}><Pressable onPress={() => persist(items.map((current) => current.id === item.id ? { ...current, done: !current.done } : current))} style={[styles.check, { borderColor: item.done ? colors.primary : colors.mutedForeground, backgroundColor: item.done ? colors.primary : 'transparent' }]}>{item.done && <Feather name="check" size={14} color={colors.primaryForeground} />}</Pressable><Text style={[styles.itemText, { color: item.done ? colors.mutedForeground : colors.foreground, textDecorationLine: item.done ? 'line-through' : 'none' }]}>{item.text}</Text><Pressable onPress={() => persist(items.filter((current) => current.id !== item.id))}><Feather name="trash-2" size={16} color={colors.mutedForeground} /></Pressable></View>} /></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20 }, heading: { fontSize: 30, fontWeight: '700', marginTop: 8 }, subheading: { fontSize: 14, marginTop: 5, marginBottom: 20 }, addRow: { borderWidth: 1, borderRadius: 17, padding: 7, flexDirection: 'row', alignItems: 'center' }, input: { flex: 1, paddingHorizontal: 11, fontSize: 14, minHeight: 40 }, add: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, list: { paddingTop: 18, gap: 9 }, empty: { textAlign: 'center', paddingVertical: 24 }, item: { borderWidth: 1, borderRadius: 15, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, check: { width: 23, height: 23, borderRadius: 8, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, itemText: { flex: 1, fontSize: 14, lineHeight: 20 } });