import { Feather } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useColors } from '@/hooks/useColors';

export default function SearchScreen() {
  const colors = useColors();
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);
  const search = () => { if (!query.trim()) return; setLoading(true); setSearched(false); setTimeout(() => { setLoading(false); setSearched(true); }, 650); };
  return <ScrollView style={[styles.screen, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><Text style={[styles.heading, { color: colors.foreground }]}>Search the web</Text><Text style={[styles.subheading, { color: colors.mutedForeground }]}>Find current answers when Jarvis needs more context.</Text><View style={[styles.searchBox, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="search" size={19} color={colors.mutedForeground} /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Search anything..." placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} /><Pressable onPress={search}><Feather name="arrow-up-right" size={19} color={colors.primary} /></Pressable></View>{loading && <View style={styles.state}><ActivityIndicator color={colors.primary} /><Text style={[styles.stateText, { color: colors.mutedForeground }]}>Searching the web...</Text></View>}{searched && <View style={[styles.result, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.resultLabel, { color: colors.primary }]}>SEARCH READY</Text><Text style={[styles.resultTitle, { color: colors.foreground }]}>Open live results for “{query}”</Text><Text style={[styles.resultBody, { color: colors.mutedForeground }]}>This first mobile slice hands the query to your browser while keeping the assistant ready for an in-app search provider next.</Text><Pressable onPress={() => Linking.openURL(`https://www.google.com/search?q=${encodeURIComponent(query)}`)} style={[styles.open, { backgroundColor: colors.primary }]}><Text style={[styles.openText, { color: colors.primaryForeground }]}>Open results</Text><Feather name="external-link" size={16} color={colors.primaryForeground} /></Pressable></View>}{!loading && !searched && <View style={[styles.suggestions, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.suggestionHeading, { color: colors.foreground }]}>Try asking Jarvis to search</Text>{['Best cafés near me', 'Today’s top headlines', 'Explain this latest trend'].map((item) => <Pressable key={item} onPress={() => { setQuery(item); }} style={[styles.suggestion, { borderTopColor: colors.border }]}><Feather name="corner-down-right" size={16} color={colors.primary} /><Text style={[styles.suggestionText, { color: colors.mutedForeground }]}>{item}</Text></Pressable>)}</View>}</ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20 }, heading: { fontSize: 30, fontWeight: '700', marginTop: 8 }, subheading: { fontSize: 14, marginTop: 5, marginBottom: 20, lineHeight: 21 }, searchBox: { borderWidth: 1, borderRadius: 17, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, input: { flex: 1, fontSize: 15 }, state: { alignItems: 'center', padding: 36, gap: 10 }, stateText: { fontSize: 13 }, result: { marginTop: 18, padding: 17, borderRadius: 18, borderWidth: 1 }, resultLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 1.4 }, resultTitle: { fontSize: 19, lineHeight: 25, fontWeight: '700', marginTop: 9 }, resultBody: { fontSize: 13, lineHeight: 20, marginTop: 9 }, open: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 12 }, openText: { fontSize: 13, fontWeight: '700' }, suggestions: { marginTop: 18, borderWidth: 1, borderRadius: 18, padding: 16 }, suggestionHeading: { fontSize: 15, fontWeight: '700', marginBottom: 5 }, suggestion: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14, borderTopWidth: 1 }, suggestionText: { fontSize: 14 } });